services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_HOSTNAME=${MONGODB_HOSTNAME}
    restart: unless-stopped